// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpryocgcmsyyqewzikzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcnlvY2djbXN5eXFld3ppa3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjc5MTIsImV4cCI6MjA2MTAwMzkxMn0.jOl5Vkf-dZ1ZcaaeXzgto2pBNAMg49ERGRl0rmnUBmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);